// Curated books and design presets matching Google Stitch designs exactly

export const BOOK_OF_THE_WEEK = {
  id: 'algorithm-of-thought',
  slug: 'the-algorithm-of-thought',
  title: 'The Algorithm of Thought',
  subtitle: 'EXPLORING COGNITIVE AI',
  author: 'Unknown Author',
  category: 'AI & Cognitive Science',
  categoryBadge: 'BOOK OF THE WEEK',
  description: 'Dive deep into the intersection of cognitive science and machine learning. This groundbreaking work explores how human thought patterns are being mirrored in the latest neural networks, offering a profound look at the future of intelligence.',
  coverTheme: 'neural-purple',
  coverType: 'brain-network',
  coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=800&auto=format&fit=crop',
  colorAccent: '#8b5cf6',
  rating: 4.9,
  totalReviews: 328,
  pages: 384,
  readTime: '6h 15m',
}

export const CONTINUE_READING_BOOKS = [
  {
    id: 'neuroplasticity-now',
    slug: 'neuroplasticity-now',
    title: 'Neuroplasticity Now',
    author: 'Dr. Aris Vance',
    progress: 64,
    timeLeft: '2h left',
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'MIND // MACHINE',
    category: 'Neuroscience',
  },
  {
    id: 'the-silicon-plains',
    slug: 'the-silicon-plains',
    title: 'The Silicon Plains',
    author: 'Elena Rostova',
    progress: 12,
    timeLeft: '8h left',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE SILICON PLAINS',
    category: 'Sci-Fi / Tech',
  },
]

export const TRENDING_BOOKS = [
  {
    rank: 1,
    id: 'data-dominance',
    slug: 'data-dominance',
    title: 'Data Dominance',
    category: 'Tech & Society',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
  },
  {
    rank: 2,
    id: 'the-rational-mind',
    slug: 'the-rational-mind',
    title: 'The Rational...',
    fullTitle: 'The Rational Mind',
    category: 'Philosophy',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
  },
  {
    rank: 3,
    id: 'form-and-void',
    slug: 'form-and-void',
    title: 'Form & Void',
    category: 'Design Theory',
    coverImage: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
  },
]

export const NEW_ARRIVALS = [
  {
    id: 'beyond-the-void',
    slug: 'beyond-the-void',
    title: 'Beyond the Void',
    author: 'K.L. Harrison',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE SILENT PATHS',
    category: 'Sci-Fi',
  },
  {
    id: 'deep-currents',
    slug: 'deep-currents',
    title: 'Deep Currents',
    author: 'M. Sato',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'DEEP CURRENTS',
    category: 'Fiction',
  },
  {
    id: 'concrete-state',
    slug: 'concrete-state',
    title: 'Concrete State',
    author: 'J.R. Black',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'CONCRETE STATE',
    category: 'Architecture',
  },
  {
    id: 'the-red-dot',
    slug: 'the-red-dot',
    title: 'The Red Dot',
    author: 'Author Unknown',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE VOID',
    category: 'Mystery',
  },
  {
    id: 'neon-rain',
    slug: 'neon-rain',
    title: 'Neon Rain',
    author: 'T. Chen',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'NEON RAIN',
    category: 'Cyberpunk',
  },
  {
    id: 'synthetic-minds',
    slug: 'synthetic-minds',
    title: 'Synthetic Minds',
    author: 'Dr. E. Turing',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'READIFY AI',
    category: 'AI & Robotics',
  },
]

export const MY_LIBRARY_BOOKS = [
  // READING TAB (In Progress)
  {
    id: 'neuromancer',
    slug: 'neuromancer',
    title: 'Neuromancer',
    author: 'William Gibson',
    progress: 65,
    category: 'SCI-FI',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'NEUROMANCER',
  },
  {
    id: 'thinking-fast-and-slow',
    slug: 'thinking-fast-and-slow',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    progress: 90,
    category: 'PSYCHOLOGY',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'COGNITION',
  },
  {
    id: 'the-name-of-the-wind',
    slug: 'the-name-of-the-wind',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    progress: 25,
    category: 'FANTASY',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f75bf938822?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE ARCHIVE',
  },
  {
    id: 'dune',
    slug: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    progress: 5,
    category: 'SCI-FI',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'REFLECTIONS',
  },
  {
    id: 'atomic-habits',
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    progress: 50,
    category: 'SELF-HELP',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'SYSTEMS',
  },

  // COMPLETED TAB
  {
    id: 'the-psychology-of-money',
    slug: 'the-psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    progress: 100,
    category: 'FINANCE',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'WEALTH',
  },
  {
    id: 'deep-work',
    slug: 'deep-work',
    title: 'Deep Work',
    author: 'Cal Newport',
    progress: 100,
    category: 'PRODUCTIVITY',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'FOCUS',
  },
  {
    id: 'zero-to-one',
    slug: 'zero-to-one',
    title: 'Zero to One',
    author: 'Peter Thiel',
    progress: 100,
    category: 'BUSINESS',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'STARTUP',
  },
  {
    id: 'steve-jobs',
    slug: 'steve-jobs',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    progress: 100,
    category: 'BIOGRAPHY',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'INNOVATION',
  },

  // TO READ TAB
  {
    id: 'sapiens',
    slug: 'sapiens',
    title: 'Sapiens: A Brief History',
    author: 'Yuval Noah Harari',
    progress: 0,
    category: 'HISTORY',
    status: 'to-read',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'HUMANKIND',
  },
  {
    id: 'foundation',
    slug: 'foundation',
    title: 'Foundation',
    author: 'Isaac Asimov',
    progress: 0,
    category: 'SCI-FI',
    status: 'to-read',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'GALACTIC',
  },
  {
    id: 'project-hail-mary',
    slug: 'project-hail-mary',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    progress: 0,
    category: 'SCI-FI',
    status: 'to-read',
    coverImage: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'SURVIVAL',
  },
  {
    id: 'clean-code',
    slug: 'clean-code',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    progress: 0,
    category: 'PROGRAMMING',
    status: 'to-read',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'CRAFTSMAN',
  },
]

export const ALL_EXPLORE_BOOKS = [
  ...MY_LIBRARY_BOOKS,
  ...NEW_ARRIVALS,
  {
    id: 'the-design-of-everyday-things',
    slug: 'the-design-of-everyday-things',
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    progress: 34,
    category: 'Design',
    coverImage: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
    description: 'A masterpiece on human-centered design and psychology.',
    totalReviews: 489,
    averageRating: 4.8,
  },
  {
    id: 'the-algorithm-of-thought',
    slug: 'the-algorithm-of-thought',
    title: 'The Algorithm of Thought',
    author: 'Unknown Author',
    progress: 0,
    category: 'AI',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=800&auto=format&fit=crop',
    description: 'Exploring cognitive artificial intelligence and human reasoning.',
    totalReviews: 328,
    averageRating: 4.9,
  },
]

export const STATS_DASHBOARD_DATA = {
  booksRead: 42,
  booksReadDelta: '+3 this month',
  hoursSpent: 128,
  hoursSpentPercentile: 'Top 15% of readers',
  dailyStreak: 14,
  streakUnit: 'Days',
  streakMessage: 'Keep it up!',
  savedBooks: [
    {
      id: 'the-quantum-age',
      slug: 'the-quantum-age',
      title: 'The Quantum Age',
      category: 'SCIENCE FICTION',
      coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=600&auto=format&fit=crop',
      badge: 'SYNTHESIS',
    },
    {
      id: 'meditations-on-time',
      slug: 'meditations-on-time',
      title: 'Meditations on Time',
      category: 'PHILOSOPHY',
      coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
      badge: 'TEMPORAL ONTOLOGY',
    },
  ],
  readingHistory: [
    {
      id: 'designing-data-intensive-applications',
      slug: 'designing-data-intensive-applications',
      title: 'Designing Data-Intensive Applications',
      lastRead: 'Last read 2 hours ago',
      progress: 85,
    },
    {
      id: 'the-lean-startup',
      slug: 'the-lean-startup',
      title: 'The Lean Startup',
      lastRead: 'Last read yesterday',
      progress: 40,
    },
  ],
}

export const READER_DEMO_BOOK = {
  id: 'the-design-of-everyday-things',
  slug: 'the-design-of-everyday-things',
  title: 'The Design of Everyday Things',
  author: 'Don Norman',
  progress: 34,
  chapters: [
    {
      id: 'ch-1',
      number: 1,
      title: '1. The Psychopathology of Everyday Things',
      subsections: [],
    },
    {
      id: 'ch-2',
      number: 2,
      title: '2. The Psychology of Everyday Actions',
      active: true,
      subsections: [
        {
          id: 'ch-2-1',
          title: 'Knowledge in the Head and in the World',
          active: true,
        },
      ],
      content: {
        chapterLabel: 'CHAPTER 2',
        title: 'The Psychology of Everyday Actions',
        paragraphs: [
          'When people use something, they face two gulfs: the Gulf of Execution, where they try to figure out how it operates, and the Gulf of Evaluation, where they try to figure out what happened. The role of the designer is to help people bridge the two gulfs.',
          'We bridge the Gulf of Execution through the use of signifiers, constraints, mappings, and a conceptual model. We bridge the Gulf of Evaluation through the use of feedback and a good conceptual model.',
        ],
        subheading: 'Knowledge in the Head and in the World',
        subheadingParagraphs: [
          'Human memory is notoriously flawed. People are apt to forget things, or to remember them incorrectly. Fortunately, we don\'t have to have all the knowledge we need in our heads. A lot of knowledge can be placed in the world.',
        ],
      },
    },
    {
      id: 'ch-3',
      number: 3,
      title: '3. Knowing What to Do',
      subsections: [],
    },
    {
      id: 'ch-4',
      number: 4,
      title: '4. To Err Is Human',
      subsections: [],
    },
  ],
}
