// Curated books and design presets matching Readify aesthetic exactly

export const BOOK_OF_THE_WEEK = {
  id: 'the-silent-stars',
  slug: 'the-silent-stars',
  title: 'The Silent Stars',
  subtitle: 'A JOURNEY INTO THE UNKNOWN • A MASTERPIECE OF SCI-FI WONDER',
  author: 'E.R. Vance',
  authorFullName: 'Elara Vance',
  category: 'Science Fiction',
  categoryBadge: 'FEATURED MASTERPIECE',
  description: 'In a forgotten corner of the cosmos, ancient signals begin to transmit across deep space. Follow the voyage of the Starfall as they uncover the secret origins of the galaxy.',
  coverTheme: 'cosmic-galaxy',
  coverType: 'galaxy-stars',
  coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
  colorAccent: '#a855f7',
  rating: 4.9,
  totalReviews: 842,
  pages: 412,
  readTime: '7h 20m',
}

export const CONTINUE_READING_BOOKS = [
  {
    id: 'atomic-habits',
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    chapter: 'Chapter 4',
    progress: 65,
    timeLeft: '2h 15m remaining',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'ATOMIC HABITS',
    category: 'Self-Help',
  },
  {
    id: 'the-silent-stars-cr',
    slug: 'the-silent-stars',
    title: 'The Silent Stars',
    author: 'Elara Vance',
    chapter: 'Chapter 12',
    progress: 42,
    timeLeft: '4h 10m remaining',
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE SILENT STARS',
    category: 'Science Fiction',
  },
]

export const TRENDING_BOOKS = [
  {
    rank: 1,
    id: 'neon-gods',
    slug: 'neon-gods',
    title: 'Neon Gods',
    subtitle: 'BOOK ONE OF THE CHRONICLES',
    author: 'Eliza Reed',
    category: 'Cyberpunk / Fantasy',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    tabletFrame: true,
  },
  {
    rank: 2,
    id: 'the-golden-ratio',
    slug: 'the-golden-ratio',
    title: 'The Golden Ratio',
    subtitle: 'A DESIGN REVOLUTION',
    author: 'Julia Wild',
    category: 'Design & Art',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop',
    tabletFrame: true,
  },
  {
    rank: 3,
    id: 'stone-heart',
    slug: 'stone-heart',
    title: 'Stone Heart',
    subtitle: 'BOOK ONE OF THE MYSTIC REALMS',
    author: 'Elara Vance',
    category: 'Epic Fantasy',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop',
    tabletFrame: true,
  },
]

export const SAVED_SHELVES = [
  { id: 'prog', name: 'Programming', count: 12, icon: 'code', color: 'from-blue-500 to-indigo-500' },
  { id: 'self', name: 'Self-Help', count: 8, icon: 'lightbulb', color: 'from-purple-500 to-pink-500' },
  { id: 'scifi', name: 'Sci-Fi & Fantasy', count: 15, icon: 'rocket', color: 'from-violet-500 to-fuchsia-500' },
  { id: 'biz', name: 'Business & Finance', count: 9, icon: 'chart', color: 'from-emerald-500 to-teal-500' },
]

export const CATALOG_PRESET_BOOKS = [
  {
    id: 'the-silicon-mirage',
    slug: 'the-silicon-mirage',
    title: 'The Silicon Mirage',
    coverTitle: 'DIGITAL ASCENT',
    author: 'A.J. Sterling',
    coverAuthor: 'ELARA VANCE',
    category: 'Tech',
    difficulty: 'Intermediate',
    readTime: '12h read',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'echoes-of-the-spire',
    slug: 'echoes-of-the-spire',
    title: 'Echoes of the Spire',
    coverTitle: 'THE VOID SPIRE',
    author: 'Elena Vance',
    coverAuthor: 'ARTHUR VANCE',
    category: 'Fiction',
    difficulty: 'Beginner',
    readTime: '8h read',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'shattered-markets',
    slug: 'shattered-markets',
    title: 'Shattered Markets',
    coverTitle: 'FRACTURED TRUST',
    author: 'Marcus Thorne',
    coverAuthor: 'ELIZA VANCE',
    category: 'Business',
    difficulty: 'Advanced',
    readTime: '5h read',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'synthetic-evolution',
    slug: 'synthetic-evolution',
    title: 'Synthetic Evolution',
    coverTitle: 'CYBERGENESIS',
    coverSubtitle: 'Decoding the Future of Life',
    author: 'Dr. Aris Thorne',
    coverAuthor: 'Dr. ELARA VANCE',
    category: 'Science',
    difficulty: 'Advanced',
    readTime: '15h read',
    rating: 4.2,
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'the-silent-stars-cat',
    slug: 'the-silent-stars',
    title: 'The Silent Stars',
    coverTitle: 'THE SILENT STARS',
    author: 'E.R. Vance',
    coverAuthor: 'ELARA VANCE',
    category: 'Fiction',
    difficulty: 'Beginner',
    readTime: '7h read',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'atomic-habits-cat',
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    coverTitle: 'ATOMIC HABITS',
    author: 'James Clear',
    coverAuthor: 'JAMES CLEAR',
    category: 'Business',
    difficulty: 'Beginner',
    readTime: '6h read',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'chronicles-of-rome',
    slug: 'chronicles-of-rome',
    title: 'Chronicles of Rome',
    coverTitle: 'ANCIENT EMPIRES',
    author: 'Marcus Aurelius',
    coverAuthor: 'M. AURELIUS',
    category: 'History',
    difficulty: 'Intermediate',
    readTime: '10h read',
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'quantum-realms',
    slug: 'quantum-realms',
    title: 'Quantum Realms',
    coverTitle: 'THE QUANTUM CODE',
    author: 'Dr. Sarah Lin',
    coverAuthor: 'SARAH LIN',
    category: 'Science',
    difficulty: 'Advanced',
    readTime: '9h read',
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=800&auto=format&fit=crop',
  },
]

export const SIMILAR_READS_PRESET = [
  {
    id: 'fractured-trust',
    slug: 'shattered-markets',
    title: 'Fractured Trust',
    author: 'Elena Rostova',
    coverTitle: 'FRACTURED TRUST',
    coverAuthor: 'KAELEN THORNE',
    category: 'Corporate Thriller',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'digital-ascent-sim',
    slug: 'the-silicon-mirage',
    title: 'Digital Ascent',
    author: 'Marcus Wei',
    coverTitle: 'DIGITAL ASCENT',
    coverAuthor: 'ELARA VANCE',
    category: 'Cyberpunk',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'echoes-of-silence',
    slug: 'echoes-of-the-spire',
    title: 'Echoes of Silence',
    author: 'Sarah Jenkins',
    coverTitle: 'THE ABYSS WATCHER',
    coverAuthor: 'ELARA VANCE',
    category: 'Sci-Fi Thriller',
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'iron-vanguard',
    slug: 'the-silent-stars',
    title: 'Iron Vanguard',
    author: 'David Oakes',
    coverTitle: "VOID'S EDGE: IRONCLAD",
    coverAuthor: 'KAELEN VANCE',
    category: 'Military Sci-Fi',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
  },
]

export const NEW_ARRIVALS = [
  {
    id: 'beyond-the-void',
    slug: 'beyond-the-void',
    title: 'Beyond the Void',
    author: 'K.L. Harrison',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE SILENT PATHS',
    category: 'Sci-Fi',
  },
  {
    id: 'deep-currents',
    slug: 'deep-currents',
    title: 'Deep Currents',
    author: 'M. Sato',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'DEEP CURRENTS',
    category: 'Fiction',
  },
  {
    id: 'concrete-state',
    slug: 'concrete-state',
    title: 'Concrete State',
    author: 'J.R. Black',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'CONCRETE STATE',
    category: 'Architecture',
  },
  {
    id: 'the-red-dot',
    slug: 'the-red-dot',
    title: 'The Red Dot',
    author: 'Author Unknown',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE VOID',
    category: 'Mystery',
  },
  {
    id: 'neon-rain',
    slug: 'neon-rain',
    title: 'Neon Rain',
    author: 'T. Chen',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'NEON RAIN',
    category: 'Cyberpunk',
  },
  {
    id: 'synthetic-minds',
    slug: 'synthetic-minds',
    title: 'Synthetic Minds',
    author: 'Dr. E. Turing',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'READIFY',
    category: 'AI & Robotics',
  },
]

export const MY_LIBRARY_BOOKS = [
  {
    id: 'neuromancer',
    slug: 'neuromancer',
    title: 'Neuromancer',
    author: 'William Gibson',
    progress: 65,
    category: 'SCI-FI',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'NEUROMANCER',
  },
  {
    id: 'thinking-fast-and-slow',
    slug: 'thinking-fast-and-slow',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    progress: 90,
    category: 'PSYCHOLOGY',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'COGNITION',
  },
  {
    id: 'the-name-of-the-wind',
    slug: 'the-name-of-the-wind',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    progress: 25,
    category: 'FANTASY',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f75bf938822?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'THE ARCHIVE',
  },
  {
    id: 'dune',
    slug: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    progress: 5,
    category: 'SCI-FI',
    status: 'to-read',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'REFLECTIONS',
  },
  {
    id: 'atomic-habits',
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    progress: 50,
    category: 'SELF-HELP',
    status: 'reading',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    coverBadge: 'SYSTEMS',
  },
]

export const STATS_DASHBOARD_DATA = {
  booksRead: 42,
  booksReadDelta: '+3 this month',
  hoursSpent: 128,
  hoursSpentPercentile: 'Top 15% of readers',
  dailyStreak: 14,
  streakUnit: 'Days',
  streakMessage: 'Keep it up!',
  savedBooks: [
    {
      id: 'the-quantum-age',
      slug: 'the-quantum-age',
      title: 'The Quantum Age',
      category: 'SCIENCE FICTION',
      coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=600&auto=format&fit=crop',
      badge: 'SYNTHESIS',
    },
    {
      id: 'meditations-on-time',
      slug: 'meditations-on-time',
      title: 'Meditations on Time',
      category: 'PHILOSOPHY',
      coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
      badge: 'TEMPORAL ONTOLOGY',
    },
  ],
  readingHistory: [
    {
      id: 'designing-data-intensive-applications',
      slug: 'designing-data-intensive-applications',
      title: 'Designing Data-Intensive Applications',
      lastRead: 'Last read 2 hours ago',
      progress: 85,
    },
    {
      id: 'the-lean-startup',
      slug: 'the-lean-startup',
      title: 'The Lean Startup',
      lastRead: 'Last read yesterday',
      progress: 40,
    },
  ],
}

export const READER_DEMO_BOOK = {
  id: 'the-design-of-everyday-things',
  slug: 'the-design-of-everyday-things',
  title: 'The Design of Everyday Things',
  author: 'Don Norman',
  progress: 34,
  chapters: [
    {
      id: 'ch-1',
      number: 1,
      title: '1. The Psychopathology of Everyday Things',
      subsections: [],
    },
    {
      id: 'ch-2',
      number: 2,
      title: '2. The Psychology of Everyday Actions',
      active: true,
      subsections: [
        {
          id: 'ch-2-1',
          title: 'Knowledge in the Head and in the World',
          active: true,
        },
      ],
      content: {
        chapterLabel: 'CHAPTER 2',
        title: 'The Psychology of Everyday Actions',
        paragraphs: [
          'When people use something, they face two gulfs: the Gulf of Execution, where they try to figure out how it operates, and the Gulf of Evaluation, where they try to figure out what happened. The role of the designer is to help people bridge the two gulfs.',
          'We bridge the Gulf of Execution through the use of signifiers, constraints, mappings, and a conceptual model. We bridge the Gulf of Evaluation through the use of feedback and a good conceptual model.',
        ],
        subheading: 'Knowledge in the Head and in the World',
        subheadingParagraphs: [
          'Human memory is notoriously flawed. People are apt to forget things, or to remember them incorrectly. Fortunately, we don\'t have to have all the knowledge we need in our heads. A lot of knowledge can be placed in the world.',
        ],
      },
    },
    {
      id: 'ch-3',
      number: 3,
      title: '3. Knowing What to Do',
      subsections: [],
    },
    {
      id: 'ch-4',
      number: 4,
      title: '4. To Err Is Human',
      subsections: [],
    },
  ],
}
